import pImg5 from '@/public/images/project/img01.png'
import pImg6 from '@/public/images/project/img02.png'
import pImg7 from '@/public/images/project/img03.png'


import icon1 from '@/public/images/icon/pro-icon01.png'
import icon2 from '@/public/images/icon/pro-icon02.png'
import icon3 from '@/public/images/icon/pro-icon03.png'

const Project = [
    {
        Id: '1',
        pImg: '/images/qatara.jpeg',
        title: 'QATARA — Univers de marque & e-commerce cosmétique',
        slug: 'qatara-univers-de-marque-e-commerce-cosmetique',
        rnumber: '75',
        rtext: 'Augmentation du trafic',
        tnumber: '120',
        ttext: 'Nouveaux clients mensuels',
        snumber: '95',
        stext: 'Taux de satisfaction client',
        description: 'Accompagnement complet de la marque QATARA : conception du logo et de l’identité visuelle, design des étiquettes produits, création de l’univers de marque, shootings produits par IA et développement d’une plateforme e-commerce immersive et cohérente',
    },
    {
        Id: '2',
        pImg: '/images/testimonial/sa-tes02.jpg',
        title: 'A2E Media — Site web corporate d’agence (Dubaï)',
        slug: 'a2e-media-site-web-corporate-agence-dubaï',
        rnumber: '60',
        rtext: 'Augmentation des réservations',
        tnumber: '85',
        ttext: 'Clients satisfaits',
        snumber: '4.9',
        stext: 'Note moyenne sur les stores',
        description: 'Développement du site web officiel de l’agence A2E Media, avec une approche orientée image de marque, clarté des contenus et expérience utilisateur, adaptée à un positionnement international et professionnel.',
    },
    {
        Id: '3',
        pImg: '/images/testimonial/sa-tes03.jpg',
        title: 'YNUT — Site web & application mobile gourmet premium',
        slug: 'ynut-site-web-app-mobile-gourmet-premium',
        rnumber: '200',
        rtext: 'Augmentation du trafic',
        tnumber: '150',
        ttext: 'Leads générés',
        snumber: '98',
        stext: 'Score de performance',
        description: 'Accompagnement global de la marque YNUT : conception de l’univers de marque, design des packagings, création de visuels produits par IA et développement d’un site e-commerce ainsi que d’une application mobile, actuellement en phase de pré-lancement.',
    },
    {
        Id: '4',
        pImg: '/images/testimonial/sa-tes04.jpg',
        title: 'Solution SaaS sur Mesure',
        slug: 'solution-saas',
        rnumber: '300',
        rtext: 'Utilisateurs actifs',
        tnumber: '40',
        ttext: 'Heures économisées/semaine',
        snumber: '99.9',
        stext: 'Taux de disponibilité',
        description: 'Développement d\'une solution SaaS personnalisée pour la gestion de projet avec tableau de bord analytique.',
    },
    {
        Id: '5',
        pImg: pImg5,
        icon: icon1,
        title: 'Stratégie SEO Internationale',
        slug: 'strategie-seo-internationale',
        rtext1: 'SEO',
        rtext2: 'Référencement',
        rtext3: 'International',
        description: 'Mise en place d\'une stratégie de référencement international pour cibler plusieurs marchés européens.',
    },
    {
        Id: '6',
        pImg: pImg6,
        icon: icon2,
        title: 'Application Mobile Événementielle',
        slug: 'app-mobile-evenementielle',
        rtext1: 'Mobile',
        rtext2: 'Événementiel',
        rtext3: 'Innovation',
        description: 'Application mobile pour la gestion et l\'interaction lors de grands événements professionnels.',
    },
    {
        Id: '7',
        pImg: pImg7,
        icon: icon3,
        title: 'Plateforme E-learning',
        slug: 'plateforme-elearning',
        rtext1: 'Éducation',
        rtext2: 'LMS',
        rtext3: 'Formation',
        description: 'Création d\'une plateforme d\'apprentissage en ligne avec suivi des progrès et certifications.',
    },
    {
        Id: '8',
        pImg: '/images/testimonial/sa-tes01.jpg',
        title: 'Marketplace B2B',
        slug: 'marketplace-b2b',
        rnumber: '500',
        rtext: 'Entreprises connectées',
        tnumber: '1.2',
        ttext: 'M€ de CA généré',
        snumber: '45',
        stext: 'Pays desservis',
        description: 'Développement d\'une marketplace B2B pour faciliter les échanges entre professionnels à l\'international.',
    },
    {
        Id: '9',
        pImg: '/images/testimonial/sa-tes02.jpg',
        title: 'Application de Gestion Immobilière',
        slug: 'app-gestion-immobiliere',
        rnumber: '80',
        rtext: 'Agences équipées',
        tnumber: '30',
        ttext: 'Processus automatisés',
        snumber: '98',
        stext: 'Clients satisfaits',
        description: 'Solution complète de gestion immobilière avec visite virtuelle et signature électronique des contrats.',
    },
]

export default Project;