import pImg5 from '@/public/images/project/img01.png'
import pImg6 from '@/public/images/project/img02.png'
import pImg7 from '@/public/images/project/img03.png'


import icon1 from '@/public/images/icon/pro-icon01.png'
import icon2 from '@/public/images/icon/pro-icon02.png'
import icon3 from '@/public/images/icon/pro-icon03.png'

const Project = [
    {
        Id: '1',
        pImg: '/images/testimonial/sa-tes01.jpg',
        title: 'Site E-commerce pour une marque de mode',
        slug: 'site-ecommerce-mode',
        rnumber: '75',
        rtext: 'Augmentation du trafic',
        tnumber: '120',
        ttext: 'Nouveaux clients mensuels',
        snumber: '95',
        stext: 'Taux de satisfaction client',
        description: 'Création d\'une plateforme e-commerce complète avec système de paiement sécurisé et gestion des stocks en temps réel.',
    },
    {
        Id: '2',
        pImg: '/images/testimonial/sa-tes02.jpg',
        title: 'Application Mobile de Réservation',
        slug: 'app-mobile-reservation',
        rnumber: '60',
        rtext: 'Augmentation des réservations',
        tnumber: '85',
        ttext: 'Clients satisfaits',
        snumber: '4.9',
        stext: 'Note moyenne sur les stores',
        description: 'Développement d\'une application mobile native pour iOS et Android permettant la réservation en temps réel de services.',
    },
    {
        Id: '3',
        pImg: '/images/testimonial/sa-tes03.jpg',
        title: 'Refonte de Site Vitrine',
        slug: 'refonte-site-vitrine',
        rnumber: '200',
        rtext: 'Augmentation du trafic',
        tnumber: '150',
        ttext: 'Leads générés',
        snumber: '98',
        stext: 'Score de performance',
        description: 'Modernisation complète d\'un site vitrine avec design responsive et optimisation pour les moteurs de recherche.',
    },
    {
        Id: '4',
        pImg: '/images/testimonial/sa-tes04.jpg',
        title: 'Solution SaaS sur Mesure',
        slug: 'solution-saas',
        rnumber: '300',
        rtext: 'Utilisateurs actifs',
        tnumber: '40',
        ttext: 'Heures économisées/semaine',
        snumber: '99.9',
        stext: 'Taux de disponibilité',
        description: 'Développement d\'une solution SaaS personnalisée pour la gestion de projet avec tableau de bord analytique.',
    },
    {
        Id: '5',
        pImg: pImg5,
        icon: icon1,
        title: 'Stratégie SEO Internationale',
        slug: 'strategie-seo-internationale',
        rtext1: 'SEO',
        rtext2: 'Référencement',
        rtext3: 'International',
        description: 'Mise en place d\'une stratégie de référencement international pour cibler plusieurs marchés européens.',
    },
    {
        Id: '6',
        pImg: pImg6,
        icon: icon2,
        title: 'Application Mobile Événementielle',
        slug: 'app-mobile-evenementielle',
        rtext1: 'Mobile',
        rtext2: 'Événementiel',
        rtext3: 'Innovation',
        description: 'Application mobile pour la gestion et l\'interaction lors de grands événements professionnels.',
    },
    {
        Id: '7',
        pImg: pImg7,
        icon: icon3,
        title: 'Plateforme E-learning',
        slug: 'plateforme-elearning',
        rtext1: 'Éducation',
        rtext2: 'LMS',
        rtext3: 'Formation',
        description: 'Création d\'une plateforme d\'apprentissage en ligne avec suivi des progrès et certifications.',
    },
    {
        Id: '8',
        pImg: '/images/testimonial/sa-tes01.jpg',
        title: 'Marketplace B2B',
        slug: 'marketplace-b2b',
        rnumber: '500',
        rtext: 'Entreprises connectées',
        tnumber: '1.2',
        ttext: 'M€ de CA généré',
        snumber: '45',
        stext: 'Pays desservis',
        description: 'Développement d\'une marketplace B2B pour faciliter les échanges entre professionnels à l\'international.',
    },
    {
        Id: '9',
        pImg: '/images/testimonial/sa-tes02.jpg',
        title: 'Application de Gestion Immobilière',
        slug: 'app-gestion-immobiliere',
        rnumber: '80',
        rtext: 'Agences équipées',
        tnumber: '30',
        ttext: 'Processus automatisés',
        snumber: '98',
        stext: 'Clients satisfaits',
        description: 'Solution complète de gestion immobilière avec visite virtuelle et signature électronique des contrats.',
    },
]

export default Project;